language: node_js
node_js: lts/*
cache:
  npm: false
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:headless || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - SAUCE_USERNAME: D2L_Stardust_UX_Chapter
  - REPO_NAME=list-item-accumulator
  - OWNER_NAME=BrightspaceUILabs
  # sauce access key
  - secure: Nhe7TBntnR8QX78OaDEVVEGat7JWCk2sbnTPyPe7rAToT3lrPhZA1oTYcD7SKrJjAqE/tptEfeMbu2oyKwTHRjQezBOdV9WDW9yXeDXSP4pf5Lf5kg8hPsxcP5uLYCp/d6oxE2/TDab9CKBApMIKDYrbXe4yxWhy86F7PULUDVA4m4SMmkJnnkqMsyzykic4eysb65bE5XB6HPp4sYUjna6kag1IfRvMFBcTi93Mfut5eCVTpMcaloTJmSd2b+zkLMEEbOFR6pmEUT8X1aou2T2oA9V07Mi8Qq1hjIE03S8GvdQpQylRpNai3oCFA3VtUkBGx9nELlyRTZD23CiQ927wSvOqjChMQ0nJ+uNlRVufsxML3XcqhTP1bPlL5lb4d/7+hSpQPrbwWwr8eKd1cQ/99fASnlyVgS7GT7uTBLkIUccXvxXKVBFFJRTuQE4Z/tb1GT5wsClnUEjOz3eCLw945eMulUEYfEEsq7bBHXn4+lTHBj9OQdhNijXmU9Bxme7dWHdsd/sjXxDe4OuRjwoC501Ah2gVdtioyWEt/2NVxSlM8CESGsDF++CPGKNlFBPk1CAo2twtCa/gWo5fzILhCgG+zT6spwwQ60zKx+7xC3SWm4o3vUf97zQpINGMhPybO9ALoD2LMwpMp4EhoHOlUa8x2XACsLkLMx2rE4Y=
  # github release token
  - secure: X7oayL2ZRq2WPtvCOzb3v9CGv/1iZJgRUWzsN0mdFEoOK54FU49UWLQMa8nI2MzGLhN2gmBsguOwF08Hc8i57iziYoBs3vIuv5cQ8aLdQQZcDoQYTpySgq6mKAt/MrSSSKD/D2EXtRpx+ptPT1TtEDKnI7lh9OXO+pg06BD0JvBXHSN6y7T8yzSvBJvDldqc0VvFR2TRr7+TCPW9i54cJwlOK9gVUN3P1B0Wj4ZnbgN5Gm/zvHIWTxMOdN9FUHyoEhxaZ2PoX7ffEFUZyYpbv8HB1op1GXsLXZD/7KM6RBZAJCa36+LxkUkP2b2n3ugY1Q3CVuSjLSFMW4u0c9iRiURfZiaEztbRO+HS0ZaKqWGilIIYW47eksyhcbi1Dq1o1bPsblHp7PjjIw98Vi24KXI1STRV4wLTWhDc9gDSjkDbWT38po1ZAhk+wyTz/EEmoEB68NTbqNprLEMtiIUPCxKPMsvGNAqsZ4fhrxJ3PB0YkyAYMZiep4HPqfPodzeMZuh3XufN0L/hCaLjvTmKcIkCVADYABMU3j1Q+AC2pWpRQMN+dRGGHGPuD0YxHBekuPwYpINkf8Or8+ct8lcPPjIRISEiouCm+bxr8mzNbmjgxZsdCmFoGHR3EicBq4bRmvS1mJ3P9hMfSoz6+Fjqz0uVoo35IehXVqUQIItKa6k=
deploy:
- provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
  # npm token 272d......8224
  - secure: HF76CBZ4xNNyGrv6NExFsYMdx9v35et3EGAGSGGw+Hw5E/3OdBGi3V/71rugEXP2KHiE5VWQYgDw5LVopHPFO90UudNHDTPQpnupX12Q4e0vKBOQZfT73uzPO4smkHYYUrq5C87Cl+X0tR0g4050KeHFOMf3ej5EPW0nrp+ybHDCK0kiEC+coJReQjOtRtBDcsWgFU2YDpLoTMHHeXIJOI4QMXB8WFODzU2OisHpneUndQJAimvRKffz5FdMSc2pmv0jbJWQa08KcEs3PU+J18cHjGabLZtwICQ5ReaDCujWBdjfoElPHYPLKFb5W+/iG0nxZyqiw3RGKNmbDuY6mhdyzDRRo9CwP55Q7Hj3OX2UU1DDd+lsih8Xk7Gpkx2Cu5Rf9Dl0pzStHuOFs8xlxr7J8leQF6pJmGlaWjt0UEG+wOYX0JHwzJ8+MX0LbcjvEOY782ZBunGBIYJI79ccvV5ymgrbi7OnlghKz1excKXL8QAx04aw0nK8ScnPX4BzG+Y64fU4y4PZvU4QIlUUmOQPLHIJLRRI7EI6SryeIy8f8xixBmdtyBanBU2zeytmoH39NIvzvqmzYK5PCHFFfNUWT6+JU9d2UxyLISl2OXnjVBKgpCGEd7EU7gGIlx+VC6YywPPmuEBD03wZstphpReKg4qxZLzovkgTCSx/PcU=
  on:
    tags: true
    repo: BrightspaceUILabs/list-item-accumulator
