language: node_js
node_js: node
cache:
  npm: false
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:headless || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - SAUCE_USERNAME: D2L_Stardust_UX_Chapter
  - REPO_NAME=list-item-accumulator
  - OWNER_NAME=BrightspaceUILabs
  # sauce access key
  - secure: Nhe7TBntnR8QX78OaDEVVEGat7JWCk2sbnTPyPe7rAToT3lrPhZA1oTYcD7SKrJjAqE/tptEfeMbu2oyKwTHRjQezBOdV9WDW9yXeDXSP4pf5Lf5kg8hPsxcP5uLYCp/d6oxE2/TDab9CKBApMIKDYrbXe4yxWhy86F7PULUDVA4m4SMmkJnnkqMsyzykic4eysb65bE5XB6HPp4sYUjna6kag1IfRvMFBcTi93Mfut5eCVTpMcaloTJmSd2b+zkLMEEbOFR6pmEUT8X1aou2T2oA9V07Mi8Qq1hjIE03S8GvdQpQylRpNai3oCFA3VtUkBGx9nELlyRTZD23CiQ927wSvOqjChMQ0nJ+uNlRVufsxML3XcqhTP1bPlL5lb4d/7+hSpQPrbwWwr8eKd1cQ/99fASnlyVgS7GT7uTBLkIUccXvxXKVBFFJRTuQE4Z/tb1GT5wsClnUEjOz3eCLw945eMulUEYfEEsq7bBHXn4+lTHBj9OQdhNijXmU9Bxme7dWHdsd/sjXxDe4OuRjwoC501Ah2gVdtioyWEt/2NVxSlM8CESGsDF++CPGKNlFBPk1CAo2twtCa/gWo5fzILhCgG+zT6spwwQ60zKx+7xC3SWm4o3vUf97zQpINGMhPybO9ALoD2LMwpMp4EhoHOlUa8x2XACsLkLMx2rE4Y=
  # github release token
  - secure: X7oayL2ZRq2WPtvCOzb3v9CGv/1iZJgRUWzsN0mdFEoOK54FU49UWLQMa8nI2MzGLhN2gmBsguOwF08Hc8i57iziYoBs3vIuv5cQ8aLdQQZcDoQYTpySgq6mKAt/MrSSSKD/D2EXtRpx+ptPT1TtEDKnI7lh9OXO+pg06BD0JvBXHSN6y7T8yzSvBJvDldqc0VvFR2TRr7+TCPW9i54cJwlOK9gVUN3P1B0Wj4ZnbgN5Gm/zvHIWTxMOdN9FUHyoEhxaZ2PoX7ffEFUZyYpbv8HB1op1GXsLXZD/7KM6RBZAJCa36+LxkUkP2b2n3ugY1Q3CVuSjLSFMW4u0c9iRiURfZiaEztbRO+HS0ZaKqWGilIIYW47eksyhcbi1Dq1o1bPsblHp7PjjIw98Vi24KXI1STRV4wLTWhDc9gDSjkDbWT38po1ZAhk+wyTz/EEmoEB68NTbqNprLEMtiIUPCxKPMsvGNAqsZ4fhrxJ3PB0YkyAYMZiep4HPqfPodzeMZuh3XufN0L/hCaLjvTmKcIkCVADYABMU3j1Q+AC2pWpRQMN+dRGGHGPuD0YxHBekuPwYpINkf8Or8+ct8lcPPjIRISEiouCm+bxr8mzNbmjgxZsdCmFoGHR3EicBq4bRmvS1mJ3P9hMfSoz6+Fjqz0uVoo35IehXVqUQIItKa6k=
deploy:
- provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
  # npm token 272d......8224
  - secure: EkTO6ZCGVx23bLvNVyVYBlDqc0dpV1cISDY6ONAeh1MrCGqN0c3KMHzZW1PrJkGtFMJ3W+tFv4cqMQI41yIpuGDLw3BQMp2JjJmENNPjvRlwucfDee0wKrpwzF0J1YVoyDgex8dQUNGGF3o9IQCB4fJD3wl9QDXDtItuYL7Ppke/Dq0eN19NiEkSLcmKfKZ/IqS4vROAihcIUozv2i6IbKJehv1G0vtIYIwpbXaC3cSJxHQU1DnlRZ2mTtnH9diqnS6t8TrTLn+KsOZHNEgncQ7A/hj480jts0XK06ROwFcFM/QRbBzKKINys0UiVH6GHSLJ/Ki49A9iywnnOpOX6xI9puRREv26sHyMmw/JJd/sACLGCu2JXgacSBWOgfUC+O0yvkDjiaxiEV2WtH+5XO2w3YQEhFbWDzT76BqMwSv2z5aspoXYFd5gr8rlRlwM/XzOqDB2ZWqiBm5RD+VrVPoKHaBOKIthXQZC/J2nryh4d8hAfG8jRQ2MB1xCxhZNHDA0OFM0MUdWrPaTkv0zxKnOp4TMfRg6FQSNf7InKF6sJfckAOpRhJDX8YMIJZ+AqXhSnRfUEbkp2lRlgKgrs0Cbbar4CpvJOal4DGj64is3x0c3EfaWsYWB9ju4LNVdEbDgRYSRBCJYj5SNy3e9Q5H4+JY55Wbbmy9VrxiedLI=
  on:
    tags: true
    repo: BrightspaceUILabs/list-item-accumulator
